# Change these first
owner: zxbxns # Your GitHub organization or username, where this repository lives
repo: status-server # The name of this repository

sites:
  - name: SCRIPT
    url: http://sc.zxbxns.me:81

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status-server
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MailStores Status-Server
  introTitle: "Welcome to our **MailStores** server status page."
  introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  navbar:
    - title: Status-Server
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
