# Change these first
owner: zxbxns # Your GitHub organization or username, where this repository lives
repo: status-server # The name of this repository

sites:
  - name: 🇲🇨 SCRIPT
    url: http://sc.zxbxns.me:81
    maxResponseTime: 5000
    expectedStatusCodes:
     - 200
     - 500
  - name: AZURE
    url: http://sg-1.mailstores.me:81
    maxResponseTime: 5000
    expectedStatusCodes:
     - 200
     - 500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zxbxns.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MailStores
  introTitle: "Welcome to our **MailStores** server status page."
  introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  navbar:
    - title: Telegram
      href: https://t.me/zxbxns
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
